  const marriedList = [
    // {
       // username1: "",
       // username2: "",
       // date: "xxxx-xx-xx", // рік-місяць-число
       // photo1: "",
       // photo2: ""
      // },
      
    ];

const container = document.getElementById("married-list"); const searchInput = document.getElementById("searchInput"); function renderPairs(pairs, isSearch = false) { container.innerHTML = ""; if (pairs.length === 0) { if (isSearch) { container.innerHTML = "<p class="bg-black col-span-full font-bold px-4 py-1 rounded text-center text-white">Нічого не знайдено</p>"; } return; } pairs.forEach(pair => { const card = document.createElement("div"); card.className = "married-card"; card.innerHTML = `<div class="pair"><img alt="${pair.username1}"src="${pair.photo1}"> <span>${pair.username1}</span></div><div class="heart">❤️</div><div class="pair"><img alt="${pair.username2}"src="${pair.photo2}"> <span>${pair.username2}</span></div><p class="date">Дата одруження: ${pair.date}</p>`; container.appendChild(card); }); } renderPairs(marriedList); searchInput.addEventListener("input", () => { const query = searchInput.value.trim().toLowerCase(); if (!query) { renderPairs(marriedList); return; } const filtered = marriedList.filter(pair => pair.username1.toLowerCase().includes(query) || pair.username2.toLowerCase().includes(query) ); renderPairs(filtered, true); }); document.addEventListener("DOMContentLoaded", () => { const totalMarried = document.querySelectorAll(".married-card").length; document.getElementById("married-total").textContent = totalMarried; }); const menuToggle = document.getElementById('menu-toggle'); const menuClose = document.getElementById('menu-close'); const sideMenu = document.getElementById('side-menu'); const overlay = document.getElementById('overlay'); menuToggle.addEventListener('click', () => { sideMenu.classList.add('open'); overlay.classList.add('active'); }); menuClose.addEventListener('click', () => { sideMenu.classList.remove('open'); overlay.classList.remove('active'); }); overlay.addEventListener('click', () => { sideMenu.classList.remove('open'); overlay.classList.remove('active'); }); sideMenu.querySelectorAll('a').forEach(link => { link.addEventListener('click', () => { sideMenu.classList.remove('open'); overlay.classList.remove('active'); }); }); document.addEventListener("DOMContentLoaded", () => { document.querySelectorAll(".toggle-row").forEach(row => { row.addEventListener("click", () => { document.querySelectorAll(".toggle-row").forEach(r => { if (r !== row) r.classList.remove("open"); }); row.classList.toggle("open"); }); }); });
